apiVersion: v1
kind: Namespace
metadata:
  name: chaosmonkey
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monkey-kill
  namespace: chaosmonkey
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modify-pods
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modify-pods-monkeykill-sa
  namespace: workloads
roleRef:
  kind: ClusterRole
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: monkey-kill
    namespace: chaosmonkey
---
apiVersion: batch/v1
kind: Job
metadata:
  name: monkey-kill
  namespace: chaosmonkey
spec:
  template:
    spec:
      serviceAccountName: monkey-kill
      containers:
      - name: monkey-kill
        image: chaos-monkey:0.0.1
        command: ['sh', '-c', "/app/chaos-monkey-script.sh"]
        env:
          - name: NAMESPACE
            value: "workloads"
          - name: NR_POD_TO_KILL
            value: "3"
          - name: TIME_INTERVAL
            value: "10"
        securityContext:
          runAsUser: 1001
          allowPrivilegeEscalation: false
      restartPolicy: Never
  backoffLimit: 2